// <auto-generated />
using System;
using DotnetWorld.ShoppingCartService.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotnetWorld.ShoppingCartService.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ShoppingCartServiceDbContext))]
    partial class ShoppingCartServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotnetWorld.ShoppingCartService.Domain.CartDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserCartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCartId");

                    b.ToTable("CartDetails");
                });

            modelBuilder.Entity("DotnetWorld.ShoppingCartService.Domain.UserCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserCarts");
                });

            modelBuilder.Entity("DotnetWorld.ShoppingCartService.Domain.CartDetail", b =>
                {
                    b.HasOne("DotnetWorld.ShoppingCartService.Domain.UserCart", "UserCart")
                        .WithMany()
                        .HasForeignKey("UserCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCart");
                });
#pragma warning restore 612, 618
        }
    }
}
